# Generated by Django 5.0.4 on 2024-04-27 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('roles', models.ManyToManyField(related_name='user_credentials', to='accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='AdminCredentials',
            fields=[
                ('admin_username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('admin_password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usercredentials')),
            ],
        ),
    ]
