# Generated by Django 5.0.4 on 2024-05-08 16:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.usercredentials')),
            ],
        ),
    ]
