# Generated by Django 5.0.4 on 2024-04-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usercredentials_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=100, unique=True)),
                ('admin_password', models.CharField(max_length=100)),
            ],
        ),
    ]
