# Generated by Django 5.0.4 on 2024-05-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_admincredentials_user_usercredentials_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercredentials',
            name='user',
        ),
    ]
